[package]
name = "trading-post"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
actix-web-validator = "5.0.1"
cdrs-tokio = "8.1.1"
chrono = { version = "0.4.26", features = ["default", "serde"] }
env_logger = "0.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.104"
structopt = "0.3.26"
structopt-derive = "0.4.18"
validator = { version = "0.16.1", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
