version: '3'

services:
  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: deploy/Dockerfile_migrations
    command: sleep 86400
    tty: true
    volumes:
      - ./migrations/:/app/migrations

  cassandra-node1:
    image: bitnami/cassandra:4.0.10
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./data/node1:/bitnami
    ports:
      - "9042:9042"

  cassandra-node2:
    image: bitnami/cassandra:4.0.10
    volumes:
      - ./data/node2:/bitnami
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=cassandra

  cassandra-node3:
    image: bitnami/cassandra:4.0.10
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./data/node3:/bitnami
